### ISSUE TITLE
support for google and facebook login

### ISSUE THREAD

**Issue by alexodus** [delay/flutter_starter#1]
Is there a plan to support login via google and facebook?

**Comment by delay** [comment]
At this time I don't plan to support it since I don't need it for my own projects.  However I did have a few functions for anonymous, google, and apple signup that I never fully implemented commented out in this auth project I did.  You may be able to use some of that as a starting point.  https://github.com/delay/flutter_firebase_auth_starter/blob/master/lib/services/auth_service.dart
