### ISSUE TITLE
remove google-services.json in android file

### ISSUE THREAD

**Issue by wiktoriasobczyk** [delay/flutter_starter#5]
Hi guys! I've read your article on medium about auth with Firebase.
I do not recommend adding google services configs files to PUBLIC repo :D because is very crucial data and with this, some person can use it:
`https://github.com/delay/flutter_starter/blob/master/android/app/google-services.json` (the same situation for iOS) 
Have a nice day!

**Comment by wiktoriasobczyk** [comment]
https://groups.google.com/g/firebase-talk/c/bamCgTDajkw/m/uVEJXjtiBwAJ <-- this is a piece of information about it 💪

**Comment by delay** [comment]
Thanks for the info. I agree it is generally a bad idea depending on the project. Since this is a sample project I included it so a user could just clone the code and run it and see how it works. Obviously a user would need to change it if they built their own project. I don't think this file would be very useful for a hacker since you couldn't do anything interesting with this project. At least I hope that's the case. Anyway thanks for the suggestion and looking out for me:-)
